import { DashboardLayout } from '../../components/layout/DashboardLayout';
/**
 * pages/ClientDashboard.tsx — Client Command Hub
 * SSE streaming plan • Health Ring • PDF export • Deliverables Studio • Approve flow
 */
import { useEffect, useState } from 'react';
import { GlassCard } from '../../components/ui/GlassCard';
import { NeoButton } from '../../components/ui/NeoButton';
import { HealthRing } from '../../components/ui/HealthRing';
import { StreamingText } from '../../components/ui/StreamingText';
import { api, streamPlan } from '../../lib/api';
import { storage, LS_KEYS } from '../../lib/storage';
import { Zap, Download, Loader2, CheckCircle, FileText } from 'lucide-react';

type Client = { _id: string; organizationName: string; category: string; healthScore: number; operationalStage: string };

export default function ClientDashboard() {
  const [client, setClient] = useState<Client | null>(null);
  const [loading, setLoading] = useState(true);
  const [stations, setStations] = useState<any[]>([]);
  const [tickets, setTickets] = useState<any[]>([]);
  const [reports, setReports] = useState<any[]>([]);

  // SSE streaming state
  const [streamText, setStreamText] = useState('');
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamDone, setStreamDone] = useState(false);

  // PDF modal
  const [pdfModal, setPdfModal] = useState<{ url: string; qr: string; hash: string } | null>(null);
  const [pdfLoading, setPdfLoading] = useState(false);

  // Deliverables Studio
  const [rephraseModal, setRephraseModal] = useState(false);
  const [rephraseText, setRephraseText] = useState('');
  const [rephraseResult, setRephraseResult] = useState('');
  const [rephraseLoading, setRephraseLoading] = useState(false);

  const cid = new URLSearchParams(location.search).get('id') || storage.get<any>(LS_KEYS.CLIENT, null)?.id;

  useEffect(() => {
    if (!cid) { setLoading(false); return; }
    Promise.all([
      api<Client>(`/clients/${cid}`).catch(() => null),
      api<{ stations: any[] }>(`/clients/${cid}/roadmap`).catch(() => ({ stations: [] } as any)),
      api<any[]>(`/clients/${cid}/tickets`).catch(() => []),
      api<any[]>(`/clients/${cid}/reports`).catch(() => []),
    ]).then(([c, r, t, reps]) => {
      if (c) setClient(c as any);
      if (r && (r as any).stations) setStations((r as any).stations);
      setTickets(Array.isArray(t) ? t : (t as any)?.data || []);
      setReports(Array.isArray(reps) ? reps : (reps as any)?.data || []);
      setLoading(false);
    });
  }, []);

  const startStream = async () => {
    setStreamText('');
    setIsStreaming(true);
    setStreamDone(false);
    try {
      await streamPlan(cid || 'demo', 'hierarchy', tok => setStreamText(s => s + tok), client?.category || 'STARTUP');
    } catch (e: any) {
      setStreamText(`{"error": "${e.message || 'Stream connection failed'}"}`);
    } finally {
      setIsStreaming(false);
      setStreamDone(true);
    }
  };

  const approve = async () => {
    if (!cid || !reports[0]?._id) {
      storage.set('999x_approved', { ts: Date.now(), clientId: client?._id });
      alert('✓ Plan approved — synced with 999x Ops Team');
      return;
    }
    try {
      await api(`/clients/${cid}/approve-report`, { method: 'POST', body: JSON.stringify({ reportId: reports[0]._id, feedback: 'Approved via Client Dashboard' }) });
      alert('✓ Plan officially approved and stamped');
    } catch { alert('Approved locally — will sync when connected'); }
  };

  const exportPdf = async () => {
    setPdfLoading(true);
    try {
      const data = await api<{ verificationHash: string; pdf: { url: string; qrData: string } }>('/ai/generate-report', {
        method: 'POST',
        body: JSON.stringify({ clientId: cid || 'demo', reportType: 'HR_RESTRUCTURING', content: { title: `Operational Report — ${client?.organizationName || '999x Demo'}`, executiveSummary: streamText.slice(0, 200) || 'Executive summary generated by 999x AI engine.' } }),
      });
      setPdfModal({ url: (data as any).pdf?.url || 'https://cdn.999x.earth/reports/demo.pdf', qr: (data as any).pdf?.qrData || 'https://999x.earth/verify/demo', hash: (data as any).verificationHash || 'demo-hash' });
    } catch (e: any) {
      alert(`Failed to generate PDF: ${e.message}`);
    } finally { setPdfLoading(false); }
  };

  const rephrase = async (tone: string) => {
    setRephraseLoading(true);
    try {
      const data = await api<{ rephrased: string }>('/ai/rephrase', { method: 'POST', body: JSON.stringify({ text: rephraseText || 'تم اعتماد تقسيم اللجان', tone }) });
      setRephraseResult((data as any).rephrased || 'تمت إعادة الصياغة بنجاح.');
    } catch { setRephraseResult('إعادة الصياغة ستكون متاحة عند الاتصال بالـ API.'); }
    finally { setRephraseLoading(false); }
  };

  if (loading) return (
    <DashboardLayout>
      <div className="space-y-4 animate-pulse">
        <div className="h-20 rounded-2xl bg-white/5" />
        <div className="grid lg:grid-cols-12 gap-6">
          <div className="lg:col-span-8 h-64 rounded-2xl bg-white/5" />
          <div className="lg:col-span-4 h-64 rounded-2xl bg-white/5" />
        </div>
      </div>
    </DashboardLayout>
  );

  if (!client) return (
    <DashboardLayout>
      <div className="flex flex-col items-center justify-center py-20 text-center">
        <div className="text-[64px] mb-4">📭</div>
        <h2 className="font-bold text-pistachio text-2xl">No Client Selected</h2>
        <p className="text-white/40 mt-2 text-[13px]">Complete the onboarding wizard to create a client profile</p>
        <NeoButton to="/onboarding" className="mt-6">Start Onboarding Wizard</NeoButton>
      </div>
    </DashboardLayout>
  );

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Operational Pulse Bar */}
        <GlassCard>
          <div className="flex flex-wrap items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-lime/30 to-violet/20 border border-lime/20 flex items-center justify-center font-black text-canvas text-[13px]">
                999x
              </div>
              <div>
                <div className="font-display font-bold text-pistachio text-[18px]">{client.organizationName}</div>
                <div className="flex items-center gap-2 mt-1">
                  <span className="font-mono text-[11px] text-white/30">{client._id}</span>
                  <span className="w-1 h-1 rounded-full bg-white/20" />
                  <span className="px-2 py-0.5 rounded-full bg-white/5 border border-white/10 text-[11px] font-mono text-white/50">{client.category}</span>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-6">
              <HealthRing score={client.healthScore} size={80} />
              <div>
                <div className="text-[10px] font-mono text-white/30">STAGE</div>
                <span className="px-3 py-1.5 rounded-full bg-lime/15 text-lime border border-lime/20 text-[12px] font-mono font-bold">{client.operationalStage}</span>
              </div>
              <div className="hidden sm:block">
                <div className="text-[10px] font-mono text-white/30">OPS LEAD</div>
                <div className="font-bold text-pistachio text-[13px]">999x Team</div>
                <div className="text-[11px] text-lime/70">↗ Response: 8 min avg</div>
              </div>
            </div>
          </div>
        </GlassCard>

        <div className="grid lg:grid-cols-12 gap-6">
          {/* Roadmap Radar */}
          <GlassCard className="lg:col-span-8">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-display font-bold text-pistachio text-[18px]">Interactive Roadmap</h2>
              <span className="px-3 py-1 rounded-full bg-lime/10 border border-lime/20 text-lime font-mono text-[11px]">Avg 11 days</span>
            </div>
            {stations.length === 0 ? (
              <div className="p-8 text-center text-white/30 border border-dashed border-white/10 rounded-2xl">
                No roadmap stations — will appear after Pulse 360° Diagnostic
              </div>
            ) : (
              <div className="space-y-3">
                {stations.map((s: any, i: number) => (
                  <div key={s.id} className={`p-4 rounded-2xl border flex items-center justify-between transition-all ${
                    s.status === 'DONE' ? 'border-lime/20 bg-lime/5'
                    : s.status === 'IN_PROGRESS' ? 'border-lime/40 bg-lime/10 shadow-[0_0_20px_rgba(163,230,53,0.1)]'
                    : 'border-white/10 bg-canvas/50'
                  }`}>
                    <div className="flex items-center gap-4">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center font-mono font-bold text-[12px] ${
                        s.status === 'DONE' ? 'bg-lime text-canvas'
                        : s.status === 'IN_PROGRESS' ? 'bg-lime/20 text-lime border border-lime/40'
                        : 'bg-white/10 text-white/40'
                      }`}>
                        {s.status === 'DONE' ? '✓' : `0${i + 1}`}
                      </div>
                      <div>
                        <div className="font-bold text-pistachio text-[14px]">{s.title}</div>
                        <div className="text-[12px] text-white/40">{s.eta}</div>
                      </div>
                    </div>
                    <span className={`px-3 py-1 rounded-full text-[11px] font-mono font-bold ${
                      s.status === 'DONE' ? 'bg-lime/15 text-lime'
                      : s.status === 'IN_PROGRESS' ? 'bg-lime/20 text-lime border border-lime/30'
                      : 'bg-white/5 text-white/40'
                    }`}>{s.status}</span>
                  </div>
                ))}
              </div>
            )}
          </GlassCard>

          {/* Right column */}
          <div className="lg:col-span-4 space-y-5">
            {/* AI Plan Generator */}
            <GlassCard>
              <h3 className="font-bold text-pistachio text-[15px] mb-3 flex items-center gap-2"><Zap className="w-4 h-4 text-lime" /> Generate AI Action Plan</h3>
              {!streamText && !isStreaming && (
                <NeoButton onClick={startStream} className="w-full">Generate Live Plan (SSE)</NeoButton>
              )}
              {(isStreaming || streamText) && (
                <div>
                  <div className="flex items-center gap-2 mb-2">
                    <div className={`w-2 h-2 rounded-full ${isStreaming ? 'bg-lime animate-pulse' : 'bg-white/20'}`} />
                    <span className="font-mono text-[10px] text-white/40">{isStreaming ? 'STREAMING...' : 'DONE'}</span>
                  </div>
                  <div className="p-3 rounded-xl bg-canvas border border-lime/20 max-h-40 overflow-auto">
                    <StreamingText text={streamText} isStreaming={isStreaming} showCursor={isStreaming} className="text-[11px]" />
                  </div>
                  {streamDone && (
                    <div className="flex gap-2 mt-3">
                      <NeoButton onClick={approve} className="flex-1 text-[12px]"><CheckCircle className="w-4 h-4" /> Approve Plan</NeoButton>
                      <NeoButton variant="glass" onClick={startStream} className="text-[12px]">↺ Regenerate</NeoButton>
                    </div>
                  )}
                </div>
              )}
            </GlassCard>

            {/* Deliverables Studio */}
            <GlassCard>
              <h3 className="font-bold text-pistachio text-[15px] mb-2 flex items-center gap-2"><FileText className="w-4 h-4 text-lime" /> Deliverables Studio</h3>
              <p className="text-[12px] text-white/50 mb-3">Select text → request AI to rephrase with a different tone</p>
              <textarea
                placeholder="Paste deliverable text to rephrase..."
                value={rephraseText}
                onChange={e => setRephraseText(e.target.value)}
                className="w-full h-20 rounded-xl px-3 py-2 bg-canvas border border-white/10 text-pistachio text-[12px] resize-none outline-none focus:border-lime/40"
              />
              <div className="flex gap-2 mt-2">
                <button onClick={() => rephrase('strict')} disabled={rephraseLoading} className="flex-1 h-9 rounded-xl bg-lime/10 border border-lime/20 text-lime text-[11px] font-bold hover:bg-lime/20 transition-all disabled:opacity-50">
                  Strict Tone
                </button>
                <button onClick={() => rephrase('simple')} disabled={rephraseLoading} className="flex-1 h-9 rounded-xl bg-white/5 border border-white/10 text-pistachio/70 text-[11px] hover:border-lime/20 transition-all disabled:opacity-50">
                  Simple Tone
                </button>
              </div>
              {rephraseResult && (
                <div className="mt-3 p-3 rounded-xl bg-canvas border border-lime/20 text-[12px] text-pistachio/80 leading-relaxed">{rephraseResult}</div>
              )}
            </GlassCard>

            {/* Tickets preview */}
            <GlassCard>
              <div className="flex justify-between items-center mb-3">
                <h3 className="font-bold text-pistachio text-[15px] flex items-center gap-2"><Zap className="w-4 h-4 text-amber-400" /> Emergency Tickets</h3>
                <span className={`px-2 py-0.5 rounded-full text-[11px] font-mono ${tickets.length > 0 ? 'bg-amber-500/15 text-amber-400' : 'bg-white/5 text-white/30'}`}>
                  {tickets.length} open
                </span>
              </div>
              {tickets.length === 0 ? (
                <div className="p-4 rounded-xl border border-dashed border-white/10 text-center text-[12px] text-white/30">No tickets — everything running smooth</div>
              ) : (
                <div className="space-y-2">
                  {tickets.slice(0, 2).map((t: any) => (
                    <div key={t._id} className={`p-3 rounded-xl border ${t.urgency === 'CRITICAL_BLOCKER' ? 'border-red-400/30 bg-red-400/5' : 'border-white/10'}`}>
                      <div className="font-bold text-pistachio text-[12px]">{t.subject}</div>
                      <div className="text-lime text-[11px] mt-1">{t.aiSuggestedSolution || 'Processing...'}</div>
                    </div>
                  ))}
                </div>
              )}
              <NeoButton to="/client/tickets" variant="glass" className="w-full mt-3 text-[12px]">View All Tickets</NeoButton>
            </GlassCard>
          </div>
        </div>

        {/* PDF Export */}
        <GlassCard>
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <h3 className="font-bold text-pistachio text-[16px] flex items-center gap-2"><FileText className="w-5 h-5 text-lime" /> Branded Executive Report</h3>
              <p className="text-white/40 text-[12px] mt-1">Export a pixel-perfect PDF with QR verification code & 999x branding</p>
            </div>
            <NeoButton onClick={exportPdf} disabled={pdfLoading}>
              {pdfLoading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</> : <><Download className="w-4 h-4" /> Export Branded PDF</>}
            </NeoButton>
          </div>
        </GlassCard>

        {/* PDF Modal */}
        {pdfModal && (
          <div className="fixed inset-0 bg-black/75 backdrop-blur-md flex items-center justify-center p-4 z-50" onClick={() => setPdfModal(null)}>
            <div className="glass-panel rounded-3xl p-7 w-full max-w-[480px]" onClick={e => e.stopPropagation()}>
              <div className="text-center">
                <div className="flex justify-center mb-3"><FileText className="w-14 h-14 text-lime/60" /></div>
                <h3 className="font-display font-bold text-pistachio text-[20px]">Report Ready!</h3>
                <p className="text-white/50 text-[13px] mt-2">Your branded 999x executive report has been generated</p>
              </div>
              <div className="mt-6 p-4 rounded-2xl bg-canvas border border-lime/20">
                <div className="text-[11px] font-mono text-white/40 mb-2">VERIFICATION HASH</div>
                <div className="font-mono text-lime text-[13px] break-all">{pdfModal.hash}</div>
                <div className="text-[11px] font-mono text-white/40 mt-3 mb-2">QR VERIFICATION URL</div>
                <div className="font-mono text-pistachio/60 text-[11px] break-all">{pdfModal.qr}</div>
              </div>
              <div className="flex gap-3 mt-5">
                <a href={pdfModal.url} target="_blank" rel="noopener noreferrer" className="flex-1">
                  <NeoButton className="w-full">Open PDF</NeoButton>
                </a>
                <NeoButton variant="glass" onClick={() => { navigator.clipboard.writeText(pdfModal.hash); }}>Copy Hash</NeoButton>
              </div>
              <button onClick={() => setPdfModal(null)} className="w-full mt-3 text-[12px] text-white/30 hover:text-white/60 transition-colors">Close</button>
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
