import { DashboardLayout } from '../../components/layout/DashboardLayout';
/**
 * pages/ClientRoadmap.tsx — Interactive Timeline
 * Visual roadmap • Expandable cards • Milestones • PDF Export
 */
import { useEffect, useState } from 'react';
import { GlassCard } from '../../components/ui/GlassCard';
import { NeoButton } from '../../components/ui/NeoButton';
import { api } from '../../lib/api';
import { storage, LS_KEYS } from '../../lib/storage';
import { Map, Download, Loader2, CheckCircle } from 'lucide-react';

export default function ClientRoadmap() {
  const [stations, setStations] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [pdfLoading, setPdfLoading] = useState(false);
  const [client, setClient] = useState<any>(null);

  const loadRoadmap = () => {
    const c = storage.get<any>(LS_KEYS.CLIENT, null);
    setClient(c);
    const cid = new URLSearchParams(location.search).get('id') || c?.id || 'demo';
    setLoading(true);
    api<{ stations: any[] }>(`/clients/${cid}/roadmap`)
      .then(d => setStations((d as any).stations || []))
      .catch((err) => {
        console.error('[ClientRoadmap] Error loading roadmap:', err);
        setStations([]);
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    loadRoadmap();
    const handleRefresh = () => loadRoadmap();
    window.addEventListener('999x:data-updated', handleRefresh);
    window.addEventListener('999x:company-changed', handleRefresh);
    return () => {
      window.removeEventListener('999x:data-updated', handleRefresh);
      window.removeEventListener('999x:company-changed', handleRefresh);
    };
  }, []);

  const downloadPdf = async () => {
    setPdfLoading(true);
    const cid = new URLSearchParams(location.search).get('id') || 'demo';
    try {
      const res = await api<{ pdf: { url: string } }>('/ai/generate-report', {
        method: 'POST',
        body: JSON.stringify({ clientId: cid, reportType: 'MONTHLY_AUDIT' }),
      } as any);
      window.open((res as any).pdf.url, '_blank');
    } catch {
      // Mock PDF download visually
      const blob = new Blob([`999x Roadmap — ${new Date().toISOString()}\n\nExecutive Report generated by 999x AI Engine.`], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = '999x_Roadmap_Report.txt';
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setPdfLoading(false);
    }
  };

  if (loading) return (
    <DashboardLayout>
      <div className="max-w-[900px] mx-auto p-6 space-y-4 animate-pulse">
        <div className="h-20 rounded-2xl bg-white/5" />
        <div className="h-64 rounded-2xl bg-white/5" />
      </div>
    </DashboardLayout>
  );

  return (
    <DashboardLayout>
      <div className="max-w-[1000px] mx-auto p-4 sm:p-6 lg:p-8 space-y-8">
        {/* Header */}
        <div className="flex flex-wrap justify-between items-start gap-4">
          <div>
            <h1 className="font-display font-black text-[28px] lg:text-[36px] text-pistachio tracking-tight">Interactive Roadmap</h1>
            <p className="text-white/50 text-[14px] mt-1 max-w-[500px]">Your strategic timeline from initial diagnostic to full operational mastery. Real-time updates directly from the 999x War Room.</p>
          </div>
          <NeoButton onClick={downloadPdf} disabled={pdfLoading}>
            {pdfLoading ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</> : <><Download className="w-4 h-4" /> Export Executive PDF</>}
          </NeoButton>
        </div>

        <GlassCard>
          {stations.length === 0 ? (
            <div className="p-12 text-center border-2 border-dashed border-white/10 rounded-3xl bg-canvas/30">
              <Map className="w-14 h-14 text-white/20 mb-4" />
              <div className="font-bold text-pistachio text-xl">No roadmap plotted yet</div>
              <div className="text-white/40 mt-2 text-[13px] max-w-[400px] mx-auto">Complete your onboarding diagnostic to generate a personalized operational timeline.</div>
              <NeoButton to="/onboarding" className="mt-6">Begin Diagnostic Wizard</NeoButton>
            </div>
          ) : (
            <div className="relative pt-6 pb-12 px-2 sm:px-8">
              {/* Vertical connecting line */}
              <div className="absolute top-0 bottom-0 left-6 sm:left-12 w-0.5 bg-gradient-to-b from-lime via-white/10 to-transparent" />

              <div className="space-y-8 relative">
                {stations.map((s: any, i: number) => {
                  const isDone = s.status === 'DONE';
                  const isCurrent = s.status === 'IN_PROGRESS';
                  const isPending = s.status === 'PENDING';
                  const isExpanded = expandedId === s.id;

                  return (
                    <div key={s.id} className="relative pl-12 sm:pl-16">
                      {/* Timeline Node */}
                      <div className={`absolute left-[-10px] sm:left-[-4px] top-4 w-8 h-8 rounded-full border-4 border-canvas flex items-center justify-center font-bold text-[12px] z-10 transition-colors ${
                        isDone ? 'bg-lime text-canvas shadow-[0_0_15px_rgba(163,230,53,0.5)]' 
                        : isCurrent ? 'bg-canvas border-lime text-lime animate-pulse shadow-[0_0_20px_rgba(163,230,53,0.3)]'
                        : 'bg-canvas border-white/20 text-white/40'
                      }`}>
                        {isDone ? <CheckCircle className="w-4 h-4 text-lime" /> : <span className="font-mono">{i + 1}</span>}
                      </div>

                      {/* Card Content */}
                      <div 
                        onClick={() => setExpandedId(isExpanded ? null : s.id)}
                        className={`p-5 rounded-2xl border transition-all duration-300 cursor-pointer ${
                          isDone ? 'bg-lime/5 border-lime/20 hover:border-lime/40' 
                          : isCurrent ? 'bg-canvas border-lime shadow-[0_0_30px_rgba(163,230,53,0.1)] scale-[1.01]'
                          : 'bg-canvas/50 border-white/10 hover:border-white/20'
                        }`}
                      >
                        <div className="flex flex-wrap justify-between items-start gap-4">
                          <div>
                            <div className="flex items-center gap-3 mb-1">
                              <span className={`text-[10px] font-mono tracking-widest ${isCurrent ? 'text-lime font-bold' : 'text-white/40'}`}>
                                PHASE 0{i + 1}
                              </span>
                              {isCurrent && <span className="px-2 py-0.5 rounded-full bg-lime/20 text-lime text-[9px] font-bold uppercase">Active</span>}
                            </div>
                            <h3 className={`font-bold text-[18px] ${isPending ? 'text-pistachio/60' : 'text-pistachio'}`}>
                              {s.title}
                            </h3>
                          </div>
                          
                          <div className="text-right shrink-0">
                            <div className={`px-3 py-1 rounded-xl text-[11px] font-mono font-bold inline-block border ${
                              isDone ? 'bg-lime/10 text-lime border-lime/20'
                              : isCurrent ? 'bg-lime text-canvas border-lime'
                              : 'bg-white/5 text-white/30 border-white/10'
                            }`}>
                              {s.status}
                            </div>
                            <div className="text-[11px] text-white/40 mt-2 font-mono">
                              ETA: {s.eta}
                            </div>
                          </div>
                        </div>

                        {/* Expandable Details Area */}
                        <div className={`overflow-hidden transition-all duration-300 ease-in-out ${isExpanded ? 'max-h-40 mt-4 opacity-100' : 'max-h-0 opacity-0'}`}>
                          <div className="pt-4 border-t border-white/10">
                            <p className="text-[13px] leading-relaxed text-pistachio/70">
                              {s.details || 'System analysis and organizational restructuring protocols are executing. Awaiting further data inputs from the ops team.'}
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </GlassCard>
      </div>
    </DashboardLayout>
  );
}
